"""Remove chat models

Revision ID: 121e76c12701
Revises: ccafd04f9fbc
Create Date: 2025-08-15 13:00:18.887021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '121e76c12701'
down_revision = 'ccafd04f9fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('chat_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_session_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chat_session_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_session_pkey'),
    sa.UniqueConstraint('session_id', name='chat_session_session_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], name=op.f('chat_message_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_pkey'))
    )
    # ### end Alembic commands ###
